config:
  target: "http://localhost:3030"
  phases:
    - duration: 1
      arrivalRate: 1
      name: Warm up
    - duration: 1
      arrivalRate: 10
      rampTo: 50
      name: Ramp up load
    - duration: 1
      arrivalRate: 100
      name: Sustained load
    - duration: 1
      arrivalRate: 1000
      name: Sustained load
scenarios:
  - name: "search"
    flow:
      - get:
          url: "/products"

# config:
#   target: 'https://artillery.io'
#   phases:
#   - duration: 60
#   arrivalRate: 20
#   defaults:
#     headers:
#       x-my-service-auth: '987401838271002188298567'
# scenarios:
# - flow:
# - get:
# url: "/docs"